documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file: ['doc/source/**/*.rst, README.rst']

maintenance:
  - any:
      - changed-files:
          - any-glob-to-any-file: ['.github/**/*', 'pyproject.toml']
testing:
  - any:
      - changed-files:
          - any-glob-to-any-file: ['tests/**']
